void updatepwd();
void initialize();
void update();
char *translate_home(char *path);
char *home_based(char *path);
int iswhitespace(char c);
void trimTrailing(char * str);
int custom_strcmp(char *a, char *b);
int count_tokens(char *input);
void removewhitespace(char *old, char *new);
int countfreq(char pattern[], char string[]);